### ISSUE TITLE
Resuming CM dev meetings and preparing CM, CM4MLOps, CM4MLPerf and CM4ABTF roadmap for Q3-Q4 2024

### ISSUE THREAD

**Issue by gfursin** [mlcommons/cm4mlops#148]
Hi Arjun,

It was great to sync with you yesterday about the on-going CM developments and the roadmap for Q3-Q4 2024 - I've added the minutes from our meeting and some ideas for further discussion here: https://github.com/mlcommons/ck/blob/master/dev/meetings/20240731.md .

Let's sync at the beginning of the next week about all those items - I hope to have more news by then...

Thanks a lot and looking forward to further discussions and developments,
Grigori

**Comment by arjunsuresh** [comment]
MLCommons has scheduled a 30 minutes weekly meeting for CM immediately after the Benchmark Infra WG meeting starting from next Tuesday. 

CM Framework task force
Tuesday, October 22 · 7:05 – 7:30pm
Time zone: Europe/London
Google Meet joining info
Video call link: https://meet.google.com/jtf-crbz-ezz
Or dial: ‪(GB) +44 20 3873 3170‬ PIN: ‪214 853 005 6654‬#
More phone numbers: https://tel.meet/jtf-crbz-ezz?pin=2148530056654
