### ISSUE TITLE
Outdated run command for retinanet

### ISSUE THREAD

**Issue by anandhu-eng** [mlcommons/cm4mlops#150]
https://github.com/mlcommons/cm4mlops/blob/9868980664db183da5de5f6dbd14f939c9b3e4b0/script/test-cm-core/src/tutorials/test_tutorial_retinanet.py#L11

Should we call the script `run-mlperf-inference-app` rather than `app-mlperf-inference` here as per what we have followed in inference documentation?

**Comment by arjunsuresh** [comment]
It is good to test the script directly even though we don't expose that to the end users.
