### ISSUE TITLE
Pass pip install arguments to cm run script

### ISSUE THREAD

**Issue by xeasonx** [mlcommons/cm4mlops#151]
I followed the documents to perform resnet50 benchmark.
```bash
cm run script --tags=run-mlperf,inference,_find-performance,_full,_r4.1 --model=resnet50 --implementation=nvidia --framework=tensorrt --category=edge --scenario=Offline --execution_mode=test --device=cuda --docker --quiet --test_query_count=1000
```
I fails when downloading packages via pip, due to the network connection problem.  So I want to provide `--proxy` argument to `pip`, how to do that?

**Comment by arjunsuresh** [comment]
if you set proxy in the shell like `export HTTP_PROXY` `cm` should use that in the workflow. Can you please try this?

**Comment by arjunsuresh** [comment]
Closing this issue for now. Please reopen it if needed.
