### ISSUE TITLE
Add "install-docker" automation recipe to install it via SUDO on Ubuntu, Debian and Red Hat

### ISSUE THREAD

**Issue by gfursin** [mlcommons/cm4mlops#16]
The procedure to install the latest docker (CPU & CUDA) is somewhat tricky for different OS. I suggest to create a script to aggregate all this knowledge in one place. It will simplify using CM workflows with MLPerf and other benchmarks via Docker.

**Comment by arjunsuresh** [comment]
We now have `get-docker` CM script.
