### ISSUE TITLE
Add checksum checks for all MLPerf inference dataset and model downloads

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/cm4mlops#167]
We need to add checksum checks for all models and datasets used in MLPerf inference. For folder downloads, we can use checksum file like done [here](https://github.com/mlcommons/cm4mlops/blob/mlperf-inference/script/get-preprocessed-dataset-criteo/_cm.json#L199)

- [x] ResNet50
- [x] DLRMv2
- [x] Stable Diffusion
- [x] LLAMA2
- [x] RetinaNet
- [x] Bert
- [x] 3d-unet
- [x] Mixtral
- [x] GPTJ

**Comment by gfursin** [comment]
Hi Arjun. Just a quick question: does the recent MD5SUM check mechanism in CM supports MacOS and Windows? Do we have some tests for Windows and MacOS in GitHub actions (I think I saw somewhere that GitHub now has Windows Server support in workflows)? Thanks!

**Comment by arjunsuresh** [comment]
Hi @gfursin the code to do the check is in python and should work on Windows too. But currently we don't have any Windows specific tests for this. We do have Windows and macOS gh actions for CM installation and ABTF inference - that covers CHECKSUM check for individual files - but nothing yet for folders.

**Comment by gfursin** [comment]
> Hi @gfursin the code to do the check is in python and should work on Windows too. But currently we don't have any Windows specific tests for this. We do have Windows and macOS gh actions for CM installation and ABTF inference - that covers CHECKSUM check for individual files - but nothing yet for folders.

Cool! Thank you! That's already a very good starting point!

**Comment by anandhu-eng** [comment]
Hi @arjunsuresh , does the env variabe `CM_EXTRACT_EXTRACTED_CHECKSUM_FILE` [here](https://github.com/GATEOverflow/cm4mlops/blob/5f234dc2b06a3c5d7024313b0abf28e3b69892dd/script/extract-file/customize.py#L128) and `CM_DOWNLOAD_CHECKSUM_FILE` [here](https://github.com/GATEOverflow/cm4mlops/blob/5f234dc2b06a3c5d7024313b0abf28e3b69892dd/script/download-file/customize.py#L143) have same goal of being the path variable to checksum file for extracted files?

**Comment by arjunsuresh** [comment]
Yes

**Comment by arjunsuresh** [comment]
@anandhu-eng sorry - I was not clear in the earlier reply. `

CM_EXTRACT_EXTRACTED_CHECKSUM_FILE` is the file having the checksums for the files inside the extracted folder. 

Even though mostly we download a single file, when we use `rclone` etc we do download a folder. `CM_DOWNLOAD_CHECKSUM_FILE` is the file having the checksums for the files inside such downloaded folder.

**Comment by anandhu-eng** [comment]
Closing the issue, as checksum for the listed models and their datasets have been added.
