### ISSUE TITLE
Specifying batch size on llama2-70B cm automation

### ISSUE THREAD

**Issue by rajesh-s** [mlcommons/cm4mlops#190]
I could not find information either in the documentation or in the cm scripts on the [batch size](https://docs.mlcommons.org/inference/benchmarks/language/llama2-70b/) that is being used to report the [results in the MLCommons database](https://mlcommons.org/benchmarks/inference-datacenter/).

1. The default batch size from the [implementation](https://github.com/mlcommons/inference/blob/c7db1c3f9a0ae0623200e05580d77a8759644812/language/llama2-70b/main.py#L26) seems to be `1`. Is the cm automation specifying a value different from this? 
2. What knobs can the user have to view the configuration used on a particular submission to ensure alignment while profiling new systems?
3. If I used the automation scripts as indicated on the documentation page, on the same hardware used in the `submissions`, should I see nearly the same performance?

**Comment by arjunsuresh** [comment]
@rajesh-s most of the inference submissions are done using Nvidia implementation. In CM we have tried to match the typical batch sizes as in the Nvidia submissions but we haven't tested all of the systems. In the CM run command you can specify `--batch_size=` to use custom batch size for Nvidia implementation.

For reference implementation I'm not sure if different batch sizes work as many things are hardwired and no one has done any submission using it.

**Comment by rajesh-s** [comment]
It would help if the batch sizes are listed atleast on the submissions which I could not find on the [results](https://mlcommons.org/benchmarks/inference-datacenter/). 

The CM run command seems to default to the batch size of `1` as I indicated above, which might be good to note in the documentation. The results vary largely on the sizes and it maybe imperative to document them.

**Comment by anandhu-eng** [comment]
Hi @rajesh-s, sorry for replying late. Have noted the required addition. 

@arjunsuresh , would it be apt to include in collapsible section  or should we give that as a tip since there is a chance of users ignoring the collapsible option.

**Comment by anandhu-eng** [comment]
Hi @rajesh-s , we have added the changes in our forks but its yet to be merged to MLCommons official inference repo. You can find the changes  [here](https://gateoverflow.github.io/inference/benchmarks/language/llama2-70b/#__tabbed_1_2).

**Comment by arjunsuresh** [comment]
Closing this issue as batch_size is now added in the documentation. Please reopen if needed.
