### ISSUE TITLE
Minimum Python version

### ISSUE THREAD

**Issue by mahmoodn** [mlcommons/cm4mlops#191]
Hi,
I get the following error for installation:
```
pip3 install cm4mlops --user
Collecting cm4mlops
  Using cached https://files.pythonhosted.org/packages/ff/16/46b9f311bb802787dee1891a63612a5e7e2b0202983d4cc658164cca3f33/cm4mlops-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mhgdidky/cm4mlops/setup.py", line 40
        elif (spec := importlib.util.find_spec(name)) is not None:
                   ^
    SyntaxError: invalid syntax

    ----------------------------------------
```
The Python3 version is `3.6.8`. I don't know if that version is the correct one. Is there a minimum version for Python3 for this package?

**Comment by arjunsuresh** [comment]
Hi @mahmoodn currently we need minimum python version 3.8.

**Comment by arjunsuresh** [comment]
This issue is fixed [in this PR](https://github.com/mlcommons/cm4mlops/pull/234/commits/edd7f41da411fc95b34059535282159773400b21) but the minimum python requirement is 3.7. Most of the CM scripts won't work with 3.6 or below.
