### ISSUE TITLE
Syncing branches: mlperf-inference -> dev -> main

### ISSUE THREAD

**Issue by gfursin** [mlcommons/cm4mlops#200]
Hi,
It seems that mlperf-inference is not in sync with dev and main branches - is it possible to sync everything to make dev and main up-to-date with mlperf-inference and vice versa.
Thanks a lot!

**Comment by arjunsuresh** [comment]
Hi @gfursin [This commit](https://github.com/mlcommons/cm4mlops/pull/203/commits/dd24a2c4cd988c494cc0da7c9ac5f3a9aea76756) is creating issue with the CLA for the merge as it is under the name `Ubuntu`. 

Also in the dev branch for `get-generic-sys-utils` - the variations are sorted in alphabetical order. Should we make this a standard for all scripts?

**Comment by gfursin** [comment]
> Hi @gfursin [This commit](https://github.com/mlcommons/cm4mlops/pull/203/commits/dd24a2c4cd988c494cc0da7c9ac5f3a9aea76756) is creating issue with the CLA for the merge as it is under the name `Ubuntu`.

Yes, I saw it and will try to fix it somehow ;) ...

> 
> Also in the dev branch for `get-generic-sys-utils` - the variations are sorted in alphabetical order. Should we make this a standard for all scripts?

I am neutral to that.

**Comment by gfursin** [comment]
Actually, CM json is usually automatically updated when we edit it via cm (such as cm update ...). In such case, it will become sorted - this is generally a preferred state. If we want to have some human-friendly order, we should use YAML ...
