### ISSUE TITLE
weekly notes

### ISSUE THREAD

**Issue by gfursin** [mlcommons/cm4mlops#201]
Hi,
Just curious if there are some (weekly) notes about the upcoming changes and updates in this repo?
Thanks!

**Comment by arjunsuresh** [comment]
Hi @gfursin currently we are working on [these issues](https://github.com/mlcommons/cm4mlops/issues/177). 

Most likely going forward, we'll be adding the weekly notes in the [Benchmark Infra Weekly minutes](https://docs.google.com/document/d/1RMAaKpETh8KWyHn8QPPYXFbZskT1C3osQ48qCARO-7M/edit)

**Comment by gfursin** [comment]
Sounds good! Thanks! Let's keep in touch about that! We are working on various CM extensions and need to keep in sync ...
