### ISSUE TITLE
Dropbox link downloads are broken on Windows

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/cm4mlops#230]
Our [Windows tests](https://github.com/mlcommons/ck/actions/runs/10904363098/job/30266390412?pr=1291#step:5:1911) are broken for dropbox URLs. If it is a certificate issue, we should add "--no-check-certificate" option for Windows+dropbox.

**Comment by anandhu-eng** [comment]
Hi @arjunsuresh , this could be due to the fact that dropbox URL uses TLS version 1.3 which is not supported in wget version 1.15 which we are using in windows. I just checked with wget version 1.21.4 and it works without addition of extra flags.

**Comment by arjunsuresh** [comment]
Nice find @anandhu-eng. But why is the backup URL not working?

**Comment by anandhu-eng** [comment]
Hi @arjunsuresh , it seems that special characters were not properly escaped for windows.

**Comment by arjunsuresh** [comment]
Thank you @anandhu-eng for the fix.
