### ISSUE TITLE
Convert _cm.json to _cm.yml

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/cm4mlops#257]
We should convert most/all of the _cm.json files to _cm.yml as having a consistent meta file format will make it easier for the development.

**Comment by gfursin** [comment]
I am ok with that. We may want to do some formatting of the YAML to make it a bit more readable but I think it can be done programmatically ...

**Comment by arjunsuresh** [comment]
Sure Grigori.

**Comment by anandhu-eng** [comment]
Hi @arjunsuresh @gfursin , are either of you working on or modifying scripts that include `_cm.json`? If so, I can open the PR after your work is completed.

**Comment by gfursin** [comment]
I need to use and update mlperf-inference as well as dev but will also wait until we sync all branches and change json->yaml. Please tell me as soon as it's done to test everything and update my forks and branches ... Thank you very much for all those clean ups and syncs - very appreciated!!!

**Comment by gfursin** [comment]
@anandhu-eng - let's do https://github.com/mlcommons/cm4mlops/issues/327 first and then do the json update ...

**Comment by anandhu-eng** [comment]
Hi @gfursin , sure.
