### ISSUE TITLE
Dataset name

### ISSUE THREAD

**Issue by anandhu-eng** [mlcommons/cm4mlops#268]
Hi @arjunsuresh , would `2014` be the correct dataset name [here](https://github.com/anandhu-eng/cm4mlops/blob/a7883fbe7e2f872523f1dd809679cf403a8ff190/script/app-mlperf-inference-mlcommons-python/customize.py#L290)?

**Comment by arjunsuresh** [comment]
It is coming from [here](https://github.com/mlcommons/inference/blob/master/text_to_image/main.py#L45)
