### ISSUE TITLE
Github Tests for MLPerf inference using self hosted runners

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/cm4mlops#279]
Using [self hosted runners](https://github.com/mlcommons/cm4mlops/issues/270) we can now add github actions which run on GPUs. Currently we have added a test for gpt mlperf reference implementation. It will be good to add tests for all other reference and Nvidia implementations on CPU/GPUs and Intel implementation on SPR.

**Comment by anandhu-eng** [comment]
Hi @arjunsuresh , I could help adding for `LLAMA2`, `DLRM` and `MIXTRAL`.

**Comment by arjunsuresh** [comment]
All reference MLPerf inference implementations are now working fine in github actions upto v4.1.
