### ISSUE TITLE
New feature(Discussion) - deletion of dependency script caches when user specifies a tag similar to `-f`

### ISSUE THREAD

**Issue by anandhu-eng** [mlcommons/cm4mlops#280]
Currently, when we remove cache by specifying the tags of the script, only the cache for that particular script is removed. 

For example, using the command:
```
cm rm cache -f --tags=get,imagenet-aux
```
will only remove the `get-dataset-imagenet-aux` cache, while the cache files for dependent scripts, such as download-file, will remain intact.

While this approach provides a good safety measure, would it be beneficial to include an option to recursively delete all the dependencies associated with a particular script?

**Comment by arjunsuresh** [comment]
Hi @anandhu-eng we use `extra_cache_tags` for this. The idea is to use some set of common tags to identify all related dependencies and we can use `cm rm cache -f --tags=<list-of-common-tags>`.

**Comment by anandhu-eng** [comment]
Thanks @arjunsuresh .
