### ISSUE TITLE
Self-hosted GH runner: User interaction needed for restricted model downloads

### ISSUE THREAD

**Issue by anandhu-eng** [mlcommons/cm4mlops#313]
The self-hosted GitHub runners would need the restricted models and datasets to already be cached, as there is no means to authenticate with Hugging Face or corresponding platforms due to the absence of user interaction in GitHub Actions. For example, LLAMA2 70B.

Potential fix:
Login to Hugging Face through Hugging Face cli when setting the system for self-hosted GitHub runner. This would store the token to cache and use every time when restricted models are downloaded.

Edit:
Hugging Face document for command line interface can be found [here](https://huggingface.co/docs/huggingface_hub/main/en/guides/cli)

**Comment by arjunsuresh** [comment]
yes @anandhu-eng . Thats a nice solution for github actions for llama2.

**Comment by anandhu-eng** [comment]
Hi @arjunsuresh , I think we have to add it for MIXTRAL-8x7B too.

**Comment by arjunsuresh** [comment]
@anandhu-eng We currently have this for both mixtral and llama2.
