### ISSUE TITLE
Check that older SCC'23 and 22 tutorials do not use external forks

### ISSUE THREAD

**Issue by gfursin** [mlcommons/cm4mlops#319]
We need to check that all the changes in the external forks of MLCommons repos used in our past SCC'22 and 23 tutorials are merged with MLCommons mainline repositories. 

We can then update these tutorials to avoid using external repositories or create branches on MLCommons repositories and use them for docs:
* https://github.com/mlcommons/ck/blob/master/docs/tutorials/scc23-mlperf-inference-bert.md#test-mlperf-bert-inference-benchmark-out-of-the-box

It is not urgent but will be good to check and agree on the common practices for CM developments.

**Comment by arjunsuresh** [comment]
Hi @gfursin for this single tutorial we are using 2-3 forks for getting various codes. But in general how can we move all the codes or forks to MLCommons? Also whenever we want to fork and external repository we can't create it under MLCommons unless we ask the support to create a new repository which is not practical. And we don't have full control over MLCommons repositories like we do have in our own repos which makes it possible to run github actions under different settings. 

So, we can move some of the forks to branch under the respective MLCommons repos where we have write access and where we don't need custom github actions - but we can't do it for all the repos.

**Comment by arjunsuresh** [comment]
Closing this issue as updating old tutorials is not worth the effort. Currently branches are used in the MLCommons inference repositories for CM specific code changes.
