### ISSUE TITLE
[20241002] regular mlperf-inference -> dev -> main sync

### ISSUE THREAD

**Issue by gfursin** [mlcommons/cm4mlops#327]
I would like to release stable version of this repo for further testing in our projects. 

@arjunsuresh and @anandhu-eng - can we please sync all the branches?

I see that mlperf-inference is  112 commits ahead of main and 45 commits behind main.

Thanks a lot!

**Comment by gfursin** [comment]
Ping ;) .

**Comment by arjunsuresh** [comment]
Hi @gfursin we are currently keeping the mlperf-inference branch stable as SCC tutorial is live and until that's over working on github Tests to test Nvidia and Intel implementations. Since currently we don't have cuda related tests here, we'll do a sync after SCC is over. We can do a release from main?

**Comment by gfursin** [comment]
I need a stable release for mlperf-inference + dev to be able to use and enhance them - I can't wait for >1 month and need to move on with projects ...  That's why we discussed before that we need to keep them regularly in sync. SCC has only 1 benchmark working on CUDA + AMD and can be easily tested manually. All other tests (Nvidia + Intel) will also profit from common changes. We have enough time to sync and test all branches.

**Comment by arjunsuresh** [comment]
Sure Grigori. Then you can sync and merge them.

**Comment by gfursin** [comment]
Sure. Should we start from merging main to mlperf-inference or mlperf-inference to main?

**Comment by arjunsuresh** [comment]
Hi @gfursin please do not do any merge into mlperf-inference branch. That's a branch we are working on. We already agreed on using different branches for developments.

**Comment by arjunsuresh** [comment]
To be discussed in the weekly CM Taskforce meeting
