### ISSUE TITLE
Docker mounts increasing as we enable download to host option for models and datasets 

### ISSUE THREAD

**Issue by anandhu-eng** [mlcommons/cm4mlops#328]
The number of docker mounts in the [app-mlperf-inference](https://github.com/mlcommons/cm4mlops/blob/9be5704bd81c999c22337abb7bbf7ac2d59ca274/script/app-mlperf-inference/_cm.yaml#L1580) script is increasing as we enable the `download to host` option for models and dataset. Is this a good practice? Alternatively, we could use a common environment variable like `CM_ML_MODEL_PATH` to mount the path. However, this would create an issue when the script is called with the `_all-models` variation, as it attempts to download multiple models for a single Docker container, causing the common environment variable to be substituted during the downloads.

Edit:
I think providing the docker mounts inside the variations solves the issue. An example is [here](https://github.com/mlcommons/cm4mlops/blob/9be5704bd81c999c22337abb7bbf7ac2d59ca274/script/app-mlperf-inference/_cm.yaml#L958)

**Comment by gfursin** [comment]
I agree that it's better not to grow global mounts for all models but to use variations for extra mounts.
