### ISSUE TITLE
Improve the user experience for running MLPerf inference

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/cm4mlops#378]
Below are some of the things to do which can improve the user experience when one tries to reproduce MLPerf inference submissions

- [x] Instead of checking out the whole inference_results repository -often GBs in size, just the code folder can be checked out - usually a few MBs only
- [x] In many cases Pytorch build happens inside the docker container and it can take hours and system resources to do this build. Since, this is happening in a fixed docker container we can replace this build with a pregenerated `whl` file thus saving time for those using the docker container

**Comment by anandhu-eng** [comment]
Hi @arjunsuresh , would there be a situation where user wants to clone the entire repository during run? If there is none, would it be better if we place `code-only` as the default variation [here](https://github.com/anandhu-eng/cm4mlops/blob/c387b61eb25218e15b63099adafce6aad8c82144/script/get-mlperf-inference-results/_cm.json#L111)
