### ISSUE TITLE
Duplicate --max-batchsize argument

### ISSUE THREAD

**Issue by Submandarine** [mlcommons/cm4mlops#414]
Sometimes when running the mlcommons-python version of the stable-diffusion inference benchmark the command includes --batch-size=... twice. e.g.
`/home/.../bin/python3 main.py  --scenario Offline --profile stable-diffusion-xl-pytorch  --dataset coco-1024 --dataset-path /root/CM/repos/local/cache/59ea53e8869d4144/install --dtype fp32 --device cuda --max-batchsize 1   --max-batchsize 1 --threads 1 --user_conf ...`
I think this is because in script/app-mlperf-inference-mlcommons-python/customize.py it gets added to `env['CM_MLPERF_LOADGEN_EXTRA_OPTIONS'] += " --max-batchsize " + str(env['CM_MLPERF_LOADGEN_MAX_BATCHSIZE'])`
and later when creating the command it gets added again together with the CM_MLPERF_LOADGEN_EXTRA_OPTIONS here
```
cmd = env['CM_PYTHON_BIN_WITH_PATH'] + " main.py " \
                " --scenario " + env['CM_MLPERF_LOADGEN_SCENARIO'] + \
                " --profile " + 'stable-diffusion-xl-pytorch ' + \
                " --dataset " + 'coco-1024' +  \
                " --dataset-path " + env['CM_DATASET_PATH_ROOT'] + \
                ' --dtype ' + env['CM_MLPERF_MODEL_PRECISION'].replace("bfloat", "bf").replace("float", "fp") + \
                " --device " + device + \
                " --max-batchsize " + max_batchsize + \
                 env['CM_MLPERF_LOADGEN_EXTRA_OPTIONS'] + \
                 scenario_extra_options + mode_extra_options + \
                " --output " + env['CM_MLPERF_OUTPUT_DIR'] + \
                " --model-path " + env['CM_ML_MODEL_PATH']
```

**Comment by arjunsuresh** [comment]
@Submandarine The issue should be fixed now.
