### ISSUE TITLE
Tests for MLPerf inference submission generation

### ISSUE THREAD

**Issue by anandhu-eng** [mlcommons/cm4mlops#439]
Hi @arjunsuresh , these are the identified tests which could help us cover various possibilities for bugs in submission generation through CM for non-CM based benchmarking method. Please feel free to add more, delete or modify them:

- [x]  Case-1: `model_maping.json` in SUT folder

- [x]  Case-2: `model_mapping.json` in individual folder

- [x]  Case-3: `model_mapping.json` not present but model name is matching with the official one in submission checker

- [x]  Case-4: `model_mapping.json` is not present but model name is mapped to official model name in submission checker. Example: resnet50 to resnet

- [x]  Case-5: Case-1 to Case-4 is not satisfied. The gh action will be successfull if the submission generation fails.

- [x]  Case-6: Case-2 but `model_mapping.json` is not present in any of the folders. The gh action will be successful if the submission generation fails.

- [x]  Case-7: `sut_info.json` is not completely filled but the SUT folder name is in required format`(hardware_name-implementation-device-framework-run_config)`

**Comment by arjunsuresh** [comment]
Nice @anandhu-eng . Cases 1-6 are for open division and so case 7 is the most important one. We use `cm-sut-info.json` and `sut-info.json`?

**Comment by anandhu-eng** [comment]
I believe we are only using `cm-sut-info.json` in our code. Let me confirm it and update the code otherwise

**Comment by arjunsuresh** [comment]
@anandhu-eng We not have `cm test script --tags=...` working and can specify test inputs like [this](https://github.com/GATEOverflow/cm4mlops/blob/mlperf-inference/script/get-generic-sys-util/_cm.json#L732). The tests are automatically triggered when the corresponding script meta file is changed.

**Comment by arjunsuresh** [comment]
Hi @anandhu-eng are these completed now?

**Comment by anandhu-eng** [comment]
Hi @arjunsuresh , case 3 and case 4 are the same. Also do we need case 6 to be in github actions? Rest all are added to inference repo.

**Comment by arjunsuresh** [comment]
yes, I think case-6 is useful to have.
