### ISSUE TITLE
Add an option to use host CM_REPO as docker_cm_repo

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/cm4mlops#455]
Currently in `cm docker script` the `cm_mlops` repo is always cloned from github. It'll be good to have an option to instead copy the specified `cm_repo` from the host machine.

**Comment by Oseltamivir** [comment]
Should we do this using an env var, CM_REPO_PATH, and checking if it is a dir with `os.path.isdir()` in [script/build-dockerfile/customize.py](https://github.com/mlcommons/cm4mlops/blob/54afe334666c8ab9383d5b98a194a6a638de581e/script/build-dockerfile/customize.py#L56)?

**Comment by arjunsuresh** [comment]
Yes. That's correct. CM_REPO_PATH must also have _cmr.yml file in its root. The instead of doing `cm pull repo` we can use COPY command in dockerfile.
