### ISSUE TITLE
mlperf_loadgen

### ISSUE THREAD

**Issue by ktotam1** [mlcommons/cm4mlops#493]
in benchmark-program, i get a crash because there is no module named "mlperf_loadgen", it seems to me this module has been renamed mlcommons_loadgen? Does anyone have the same error or does this need to be fixed or is it due to doing something wrong in the set up? 
Thanks

**Comment by arjunsuresh** [comment]
Hi @ktotam1 can you please share the run command you had tried?

**Comment by ktotam1** [comment]
I ran: 
python3 -m venv cm
source cm/bin/activate
cm run script --tags=install,python-venv --name=mlperf
export CM_SCRIPT_EXTRA_CMD="--adr.python.name=mlperf"
cm run script --tags=run-mlperf,inference,_find-performance,_full,_r4.1-dev \
   --model=resnet50 \
   --implementation=intel \
   --framework=pytorch \
   --category=datacenter \
   --scenario=Offline \
   --execution_mode=test \
   --device=cpu  \
   --quiet \
   --test_query_count=1000
the output:


File "/home/user/CM/repos/local/cache/9001c0d666a84568/inference/vision/classification_and_detection/python/main.py", line 20, in <module>
    import mlperf_loadgen as lg
ModuleNotFoundError: No module named 'mlperf_loadgen'
CM error: Portable CM script failed (name = benchmark-program, return code = 256)

**Comment by ktotam1** [comment]
since then i've tried buildingmlperf_loadgen myself from https://github.com/mlcommons/inference/blob/master/loadgen/README_BUILD.md 
which has the new mlcommons_loadgen name, so it didnt work, and I tried renaming the package to mlperf_loadgen myself, and somehow it still doesnt recognize it.

**Comment by arjunsuresh** [comment]
Thank you. Let me try it - its been a while since we have run Intel implementation and we are yet to add it to our nightly runs. But strangely the line `/home/user/CM/repos/local/cache/9001c0d666a84568/inference/vision/classification_and_detection/python/main.py` should come for the reference implementation and not the Intel one. But let me confirm anyway.

**Comment by ktotam1** [comment]
Oh I'm sorry I just realized I accidentally ran it with implementation=reference and not intel, my bad. I'll update if it works once it downloaded all the necessary dependancies.

**Comment by arjunsuresh** [comment]
No worries. Even for the `reference` implementation it should have worked. I think it somehow missed the `loadgen` dependency. One reason for this can be `pip uninstall mlperf_loadgen` in which case currently we need to manually do `cm rm cache --tags=loadgen -f`. 

I believe both `mlperf_loadgen` and `mlcommons_loadgen` should work - `mlocommons_loadgen` is used now as someone already used `mlperf_loadgen` for a pypi package :)

**Comment by arjunsuresh** [comment]
Yes, it is better to use the "--docker" option to run the inference inside a docker container as it has system dependencies. `ubuntu-22.04` is the only tested OS I believe.

**Comment by ktotam1** [comment]
with docker it works, thanks!

**Comment by arjunsuresh** [comment]
Hope this issue is resolved. Feel free to reopen if required.
