### ISSUE TITLE
TypeError: get_performance_metric() missing 2 required positional arguments: 'division' and 'system_json'

### ISSUE THREAD

**Issue by zixianwang2022** [mlcommons/cm4mlops#541]
Hi, 

We are experiencing the following error when running the second time with `--rerun` after we ran the first time. 

```
New config stored in /work1/zixian/ziw081/CM/repos/local/cache/43d2d6e358274041/t008_004.hpcfund/reference-implementation/rocm-device/pytorch-framework/framework-version-v2.6.0.dev20241110/scc24-main-config.yaml
Traceback (most recent call last):
  File "/work1/zixian/ziw081/miniconda3/envs/mlperf_mgx/bin/cm", line 8, in <module>
    sys.exit(run())
  File "/work1/zixian/ziw081/miniconda3/envs/mlperf_mgx/lib/python3.10/site-packages/cmind/cli.py", line 37, in run
    r = cm.access(argv, out='con')
  File "/work1/zixian/ziw081/miniconda3/envs/mlperf_mgx/lib/python3.10/site-packages/cmind/core.py", line 754, in access
    r = action_addr(i)
  File "/work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/automation/script/module.py", line 211, in run
    r = self._run(i)
  File "/work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/automation/script/module.py", line 1487, in _run
    r = customize_code.preprocess(ii)
  File "/work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/run-mlperf-inference-app/customize.py", line 246, in preprocess
    r = cm.access(ii)
  File "/work1/zixian/ziw081/miniconda3/envs/mlperf_mgx/lib/python3.10/site-packages/cmind/core.py", line 1661, in access
    return cm.access(i)
  File "/work1/zixian/ziw081/miniconda3/envs/mlperf_mgx/lib/python3.10/site-packages/cmind/core.py", line 754, in access
    r = action_addr(i)
  File "/work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/automation/script/module.py", line 211, in run
    r = self._run(i)
  File "/work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/automation/script/module.py", line 1562, in _run
    r = prepare_and_run_script_with_postprocessing(run_script_input)
  File "/work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/automation/script/module.py", line 4855, in prepare_and_run_script_with_postprocessing
    rr = run_postprocess(customize_code, customize_common_input, recursion_spaces, env, state, const,
  File "/work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/automation/script/module.py", line 4905, in run_postprocess
    r = customize_code.postprocess(ii)
  File "/work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/app-mlperf-inference/customize.py", line 245, in postprocess
    result, valid, power_result = mlperf_utils.get_result_from_log(env['CM_MLPERF_LAST_RELEASE'], model, scenario, output_dir, mode, env.get('CM_MLPERF_INFERENCE_SOURCE_VERSION'))
  File "/work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/get-mlperf-inference-utils/mlperf_utils.py", line 28, in get_result_from_log
    result_ = checker.get_performance_metric(config, mlperf_model, result_path, scenario)
TypeError: get_performance_metric() missing 2 required positional arguments: 'division' and 'system_json'
```

We have been deleting the cache after each run to be able to rerun with cm run script, but if we want to rerun with `--rerun`, we will always get the above error.

**Comment by Squidwarder** [comment]
To add upon the previous response, the error occurred in the **accuracy** evaluation part of the script. The **performance** evaluation worked fine with `--rerun`, but when it switches over to **accuracy** we encounter the above error.

**Comment by arjunsuresh** [comment]
Hi @zixianwang2022, are you using a fork of the inference repository? If so please update it with the main one.

**Comment by Squidwarder** [comment]
Hi @arjunsuresh , below is the code we used to run the CM script:

```
    cm rm cache --tags=inference,src -f
    cm rm cache --tags=inference -f
    cm rm cache --tags=python -f
    cm pull repo

    cm run script --tags=run-mlperf,inference,_r4.1-dev,_scc24-main \
        --model=sdxl \
        --framework=pytorch \
        --category=datacenter \
        --scenario=Offline \
        --execution_mode=test \
        --device=rocm \
        --quiet --precision=float16 \
        --adr.mlperf-implementation.tags=_branch.yalu,_repo.https://github.com/zixianwang2022/mlperf-scc24 --adr.mlperf-implementation.version=custom  --env.CM_GET_PLATFORM_DETAILS=no
```

As you could see, we're removing the cache and pulling from the repo before running the `cm run script` command for our runs. Our current issue is that since the cache contains some very large files, we don't want to download them all over again for each run, thus we want to ideally remove the first 4 lines (after running them once). However, after running all of the above code once, if we try to only run the `cm run script` part we'd run into `TypeError: get_performance_metric() missing 2 required positional arguments: 'division' and 'system_json'`. How can we resolve this issue?

**Comment by Squidwarder** [comment]
Hi @arjunsuresh, the unfortunately two methods you stated above didn't work for us, we're still experiencing `TypeError: get_performance_metric() missing 2 required positional arguments: 'division' and 'system_json'`.

I've checked that the `tools/submission` directory is synced to our repo, so it doesn't look like it's a problem with that. Below is the code I ran:
```sh
cm run script --rerun --tags=run-mlperf,inference,_r4.1-dev,_scc24-main \
        --model=sdxl \
        --framework=pytorch \
        --category=datacenter \
        --scenario=Offline \
        --execution_mode=test \
        --device=rocm \
        --quiet --precision=float16 \
        --adr.mlperf-implementation.tags=_branch.yalu,_repo.https://github.com/zixianwang2022/mlperf-scc24 --adr.mlperf-implementation.version=custom  --env.CM_GET_PLATFORM_DETAILS=no \
        --adr/inference-src.tags=_repo.https://github.com/mlcommons/inference
```

**Comment by arjunsuresh** [comment]
I can see the difference, so check again 😇

**Comment by Squidwarder** [comment]
Hi @arjunsuresh , we did change all the files of `inference/tools/submission` for the `yalu` branch. Are you looking at the right branch (note, I am **not** running this on `main`) or am I still missing something belonging to some other folders?

**Comment by arjunsuresh** [comment]
My bad. I missed the branch. Yes, now the tools directory is updated. Can you please update the loadgen directory too as the VERSION file is inside that? Then clear inference,src and inference,loadgen from the cache just to be safe.

**Comment by Squidwarder** [comment]
Thank you for that. I'll let you know how that goes. On a side note, when we're currently running with the script above, the `--performance` portion of the test only runs for 10 images (whereas the default pytorch safetensors backend run for 500 images). Any idea what might be affecting this? 

Below is the parameters passed to `main.py`:
```
INFO:main:Namespace(dataset='coco-1024', dataset_path='/work1/zixian/youyang1/CM/repos/local/cache/6c690af8466d4e74/install', profile='stable-diffusion-xl-pytorch',
scenario='Offline', max_batchsize=1, threads=1, accuracy=False, find_peak_performance=False, backend='migraphx', model_name='stable-diffusion-xl',
output='/work1/zixian/youyang1/CM/repos/local/cache/59ee7d4845f94fd4/test_results/t008_010.hpcfund-reference-rocm-pytorch-v2.6.0.dev20241111-scc24-main/stable-diffusion-xl/offline/performance/run_1',
qps=1, model_path='/work1/zixian/youyang1/CM/repos/local/cache/1fc90b92e3f247d5/stable_diffusion_fp16', dtype='fp16', device='cuda',
 latent_framework='torch', mlperf_conf='mlperf.conf', user_conf='/work1/zixian/youyang1/CM/repos/mlcommons@cm4mlops/script/generate-mlperf-inference-user-conf/tmp/d9d80191874d4e7ea3d00bc7a265f4e0.conf',
audit_conf='audit.config', gpu_num=4,
ids_path='/work1/zixian/youyang1/CM/repos/local/cache/6c690af8466d4e74/install/sample_ids.txt', time=None, count=None, debug=False, performance_sample_count=1000, max_latency=None, samples_per_query=8)
```

**Comment by arjunsuresh** [comment]
No worries. Whats the contents on the user.conf file?

**Comment by Squidwarder** [comment]
Below is our `user.conf` file:
```
stable-diffusion-xl.Offline.min_query_count = 500
stable-diffusion-xl.Offline.max_query_count = 500
```

**Comment by arjunsuresh** [comment]
Then it should be some issue in the backend code. user.conf is the only one controlling the count outside of the implementation.

**Comment by Squidwarder** [comment]
Understood, I'll look into that. And back on the main issue: do I get the changes from `tools` and `loadgen` directory from the `dev` branch? Because it says that's last updated two days ago and I want to ensure that we obtain the latest change (which should hopefully fix things).

**Comment by arjunsuresh** [comment]
You can take them from the master branch too. These changes were done almost a month back.

**Comment by arjunsuresh** [comment]
Hope this issue is resolved. Feel free to reopen if required.
