### ISSUE TITLE
Running MLPerf on multiple GPU nodes

### ISSUE THREAD

**Issue by ChloeCrozier** [mlcommons/cm4mlops#545]
I have been running the MLPerf sdxl benchmark on our cluster. We are running the container on a GPU node, however when the benchmark is running, nvidia-smi shows that we are only using 1 of 4 A100s within that specific GPU.
Some of the scripts within the container accurately identified each GPU during run time. Is there a flag I need to add or a configuration file I need to edit within the container to run on multiple gpus within the same node?

**Comment by arjunsuresh** [comment]
Hi, are you using Nvidia implementation or the reference one? If its reference implementation, then the implementation will need changes to support multiple GPUs.

**Comment by ChloeCrozier** [comment]
Yes, I was using the Nvidia implementation. So, I will use the flag --implementation=reference, then do I add additional flags like --gpu_name=A100 and --num_gpus=4?

**Comment by arjunsuresh** [comment]
If you are using Nvidia implementation it's supposed to run on all the GPUs in that node without any extra arguments or code change.

**Comment by ChloeCrozier** [comment]
Interesting. Do you have an idea why it might be able to identify the IDs of all four GPUs within the node, but then only run at 100% on the 0th one?

**Comment by arjunsuresh** [comment]
Can you please share the console log when this is happening? It's in the actual run stage right?

**Comment by ChloeCrozier** [comment]
<img width="737" alt="image" src="https://github.com/user-attachments/assets/b9e2ae72-6b6b-4392-bf03-0414a09ec01e">

**Comment by arjunsuresh** [comment]
@ChloeCrozier that result is from the "reference" implementation as the heading shows. And reference implementation by default runs only on a single GPU.

**Comment by arjunsuresh** [comment]
Sure @ChloeCrozier you are aware of how to run Nvidia implementation right?

**Comment by ChloeCrozier** [comment]
Yes, thank you so much!
