### ISSUE TITLE
How to Set target.Offline.qps in CM Script? 

### ISSUE THREAD

**Issue by zixianwang2022** [mlcommons/cm4mlops#549]
Hello, 

We have been using CM scripts to run SDXL for scc_main. However, we observed that all our qps will be set only by running the 10 samples distributed. Then our formal run will be bounded by the qps results when running the 10 samples, despite our actual performance will be better than the qps tested on the 10 samples

So is there a way to set target.Offline.qps in command line in running the CM script?

**Comment by arjunsuresh** [comment]
Hi @zixianwang2022 can you use `--test_query_count=50` or `--test_query_count=500` respectively for the base and main?

**Comment by arjunsuresh** [comment]
Target qps can be set using `--target_qps=0.1` but `test_query_count` is the best option here.

**Comment by arjunsuresh** [comment]
Hope this issue is resolved. Feel free to reopen if required.
