### ISSUE TITLE
MLPerf sdxl "not supported between instances of 'str' and 'int'"

### ISSUE THREAD

**Issue by ChloeCrozier** [mlcommons/cm4mlops#566]
Hello! I am trying to run MLPerf for sdxl, but I keep running into issues with a typing error within **/root/CM/repos/mlcommons@cm4mlops/automation/script/module.py**

<img width="809" alt="image" src="https://github.com/user-attachments/assets/bc62e7c1-1651-40d4-8ef4-d45cb9e2244e">

Here is the command I ran:

<img width="720" alt="image" src="https://github.com/user-attachments/assets/ba7ea56d-4642-4988-9171-fb210b1e908d">

Are there any flags to get around this issues, or do I manually have to edit the file within the container?

**Comment by arjunsuresh** [comment]
Hi @ChloeCrozier sorry for that. Can you please do `cm pull repo` and retry?

**Comment by ChloeCrozier** [comment]
Yes, thank you, that fixed it!
